person:
  age: 10
  name: hello
  birthday: 2010/10/1
  sex: false
  hobbie: ["aaa","bbb"]
  skills:
    aaa,
    bbb,
    ccc
  location:
    "k1": 111
    "k2": "dfjakdjflas"
    "k3": [1,2,3,4,5,6,7,8]